'use strict';

const { generateMarkdown } = require('./markdown');

function makeStats(overrides = {}) {
  const formatDate = (d) => d ? d.toLocaleDateString('en-GB', { day: '2-digit', month: 'short', year: 'numeric' }) : '';
  return {
    transactions: [
      { date: new Date(2025, 0, 1), dateStr: '01/01/2025', description: 'Salary', category: 'Income', amount: 2000, balance: 3000 },
      { date: new Date(2025, 0, 5), dateStr: '05/01/2025', description: 'Tesco', category: 'Groceries', amount: -50, balance: 2950 },
    ],
    currency: '£',
    count: 2,
    totalCredits: 2000,
    totalDebits: -50,
    net: 1950,
    dateFrom: new Date(2025, 0, 1),
    dateTo: new Date(2025, 0, 5),
    monthly: [{ key: '2025-01', label: 'January 2025', credits: 2000, debits: -50, count: 2 }],
    categories: [
      { name: 'Groceries', total: -50, count: 1 },
      { name: 'Income', total: 2000, count: 1 },
    ],
    topDebits: [{ date: new Date(2025, 0, 5), dateStr: '05/01/2025', description: 'Tesco', amount: -50 }],
    topCredits: [{ date: new Date(2025, 0, 1), dateStr: '01/01/2025', description: 'Salary', amount: 2000 }],
    formatDate,
    ...overrides
  };
}

describe('generateMarkdown', () => {
  const cols = { date: 'Date', description: 'Description', amount: 'Amount', category: 'Category', balance: 'Balance' };

  test('includes title with filename', () => {
    const md = generateMarkdown(makeStats(), 'export.csv', cols);
    expect(md).toContain('# Financial Transactions: export.csv');
  });

  test('includes date range and transaction count', () => {
    const md = generateMarkdown(makeStats(), 'export.csv', cols);
    expect(md).toContain('2 transactions');
    expect(md).toContain('Jan 2025');
  });

  test('includes summary table with correct totals', () => {
    const md = generateMarkdown(makeStats(), 'export.csv', cols);
    expect(md).toContain('£2,000.00');
    expect(md).toContain('-£50.00');
    expect(md).toContain('£1,950.00');
  });

  test('includes monthly breakdown section', () => {
    const md = generateMarkdown(makeStats(), 'export.csv', cols);
    expect(md).toContain('## Monthly Breakdown');
    expect(md).toContain('January 2025');
  });

  test('includes category breakdown section', () => {
    const md = generateMarkdown(makeStats(), 'export.csv', cols);
    expect(md).toContain('## Category Breakdown');
    expect(md).toContain('Groceries');
    expect(md).toContain('Income');
  });

  test('includes notable transactions section', () => {
    const md = generateMarkdown(makeStats(), 'export.csv', cols);
    expect(md).toContain('## Notable Transactions');
    expect(md).toContain('### Largest Debits');
    expect(md).toContain('### Largest Credits');
  });

  test('includes all transactions table', () => {
    const md = generateMarkdown(makeStats(), 'export.csv', cols);
    expect(md).toContain('## All Transactions');
    expect(md).toContain('Salary');
    expect(md).toContain('Tesco');
  });

  test('escapes pipe characters in descriptions', () => {
    const stats = makeStats({
      transactions: [
        { date: new Date(2025, 0, 1), dateStr: '01/01/2025', description: 'A | B', category: '', amount: 10, balance: null }
      ],
      categories: [],
      topDebits: [],
      topCredits: [{ date: new Date(2025, 0, 1), dateStr: '01/01/2025', description: 'A | B', amount: 10 }]
    });
    const md = generateMarkdown(stats, 'test.csv', cols);
    expect(md).toContain('A \\| B');
  });

  test('uses correct currency symbol', () => {
    const stats = makeStats({ currency: '$' });
    const md = generateMarkdown(stats, 'export.csv', cols);
    expect(md).toContain('$2,000.00');
    expect(md).not.toContain('£2,000.00');
  });

  test('omits category section when no categories', () => {
    const stats = makeStats({ categories: [] });
    const md = generateMarkdown(stats, 'export.csv', { ...cols, category: null });
    expect(md).not.toContain('## Category Breakdown');
  });

  test('includes generated-by footer', () => {
    const md = generateMarkdown(makeStats(), 'export.csv', cols);
    expect(md).toContain('Generated by csvbase');
  });
});
