'use strict';

function makeFmt(currency) {
  return function fmt(n) {
    const abs = Math.abs(n).toFixed(2).replace(/\B(?=(\d{3})+(?!\d))/g, ',');
    return n < 0 ? `-${currency}${abs}` : `${currency}${abs}`;
  };
}

function esc(str) {
  return (str || '').replace(/\|/g, '\\|');
}

function generateMarkdown(stats, fileName, cols) {
  const {
    transactions, currency, count, totalCredits, totalDebits, net,
    dateFrom, dateTo, monthly, categories, topDebits, topCredits, formatDate,
  } = stats;

  const fmt = makeFmt(currency);
  const lines = [];

  const dateRangeStr = dateFrom && dateTo
    ? `${formatDate(dateFrom)} – ${formatDate(dateTo)}`
    : 'unknown date range';

  lines.push(`# Financial Transactions: ${fileName}`);
  lines.push(`*${dateRangeStr} · ${count} transactions*`);
  lines.push('');

  // Summary
  lines.push('## Summary');
  lines.push('');
  lines.push('| | Amount |');
  lines.push('|---|---:|');
  lines.push(`| Total money in | ${fmt(totalCredits)} |`);
  lines.push(`| Total money out | ${fmt(totalDebits)} |`);
  lines.push(`| Net | **${fmt(net)}** |`);
  lines.push('');

  // Monthly breakdown
  if (monthly.length > 0) {
    lines.push('## Monthly Breakdown');
    lines.push('');
    lines.push('| Month | Money In | Money Out | Net | Transactions |');
    lines.push('|---|---:|---:|---:|---:|');
    for (const m of monthly) {
      lines.push(`| ${m.label} | ${fmt(m.credits)} | ${fmt(m.debits)} | ${fmt(m.credits + m.debits)} | ${m.count} |`);
    }
    lines.push('');
  }

  // Category breakdown
  if (categories.length > 0) {
    lines.push('## Category Breakdown');
    lines.push('');
    lines.push('| Category | Total | Transactions |');
    lines.push('|---|---:|---:|');
    for (const c of categories) {
      lines.push(`| ${esc(c.name)} | ${fmt(c.total)} | ${c.count} |`);
    }
    lines.push('');
  }

  // Notable transactions
  if (topDebits.length > 0 || topCredits.length > 0) {
    lines.push('## Notable Transactions');
    lines.push('');

    if (topDebits.length > 0) {
      lines.push('### Largest Debits');
      lines.push('');
      lines.push('| Date | Description | Amount |');
      lines.push('|---|---|---:|');
      for (const t of topDebits) {
        lines.push(`| ${formatDate(t.date) || t.dateStr} | ${esc(t.description)} | ${fmt(t.amount)} |`);
      }
      lines.push('');
    }

    if (topCredits.length > 0) {
      lines.push('### Largest Credits');
      lines.push('');
      lines.push('| Date | Description | Amount |');
      lines.push('|---|---|---:|');
      for (const t of topCredits) {
        lines.push(`| ${formatDate(t.date) || t.dateStr} | ${esc(t.description)} | ${fmt(t.amount)} |`);
      }
      lines.push('');
    }
  }

  // Full transaction table
  lines.push('## All Transactions');
  lines.push('');

  const hasCategory = categories.length > 0 || (cols.category && transactions.some(t => t.category));
  const hasBalance = transactions.some(t => t.balance != null);
  const hasReference = cols.reference && transactions.some(t => t.reference);

  const headerCols = ['Date', 'Description'];
  if (hasCategory) headerCols.push('Category');
  if (hasReference) headerCols.push('Reference');
  headerCols.push('Amount');
  if (hasBalance) headerCols.push('Balance');

  lines.push(`| ${headerCols.join(' | ')} |`);
  const aligns = headerCols.map(h => (h === 'Amount' || h === 'Balance') ? '---:' : '---');
  lines.push(`| ${aligns.join(' | ')} |`);

  for (const t of transactions) {
    const row = [formatDate(t.date) || t.dateStr, esc(t.description)];
    if (hasCategory) row.push(esc(t.category));
    if (hasReference) row.push(esc(t.reference));
    row.push(fmt(t.amount));
    if (hasBalance) row.push(t.balance != null ? fmt(t.balance) : '');
    lines.push(`| ${row.join(' | ')} |`);
  }

  lines.push('');
  lines.push('---');
  lines.push(`*Generated by csvbase on ${new Date().toLocaleString('en-GB')}*`);

  return lines.join('\n');
}

module.exports = { generateMarkdown };
